model:
    arch: frrnB
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /local/patrick/datasets/cityscapes
training:
    train_iters: 85000
    batch_size: 1
    val_interval: 500
    print_interval: 25
    optimizer:
        name: 'sgd'
        lr: 1.0e-4
    l_rate: 1.0e-4
    lr_schedule:
        name: constant_lr
    momentum: 0.99
    weight_decay: 0.0005
    resume: frrnB_cityscapes_best_model.pkl
    visdom: False
    n_workers: 16

    loss:
        name: 'cross_entropy'